services:
  backend:
    build: .
    ports:
      - "${PORT}:3001" 
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public"
    env_file:
      - .env 
    depends_on:
      - db
    networks:
      - minha-rede

  db:
    image: postgres:15-trixie
    environment:
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}         
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - minha-rede
    ports:
      - "${DB_PORT}:5432"
networks:
  minha-rede:
    driver: bridge

volumes:
  db-data:
    driver: local