services:
  backend:
    build: . 
    ports:
      - "3001:3001" 
    environment:
      DATABASE_URL: "postgresql://pedidos:minipedidos25@db:5432/mini_pedidos"
    env_file:
      - .env
    depends_on:
      - db 
    networks:
      - minha-rede

  db:
    image: postgres:15-trixie
    environment:
      POSTGRES_USER: pedidos
      POSTGRES_PASSWORD: minipedidos25
      POSTGRES_DB: mini_pedidos
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - minha-rede
    ports:
    - "5432:5432"

networks:
  minha-rede:
    driver: bridge

volumes:
  db-data:
    driver: local